name: Static analysis

on: [push, pull_request]

jobs:
  psalm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        env:
          COMPOSER_ROOT_VERSION: dev-master

      - name: Run Psalm (& publish to shepherd)
        run: composer run-script stan
