name: Static Analysis

on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  Psalm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache composer dependencies
      uses: actions/cache@v1.1.0
      with:
        path: vendor
        key: composer@${{ hashFiles('**/composer.lock') }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      env:
        COMPOSER_ROOT_VERSION: dev-master

    - name: Run Psalm (& publish to shepherd)
      run: composer run-script stan
