name: Tests

on:
  push:
    paths-ignore:
      - 'docs/**'

jobs:
  PHPUnit:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        php-version: [ '8.0.1' ]

    runs-on: ${{ matrix.os }}

    env:
      COMPOSER_NO_INTERACTION: 1

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: xdebug
        tools: composer:v2
      env:
        fail-fast: true

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache composer dependencies
      uses: actions/cache@v2
      with:
        path: vendor
        key: composer@${{ hashFiles('**/composer.lock') }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      env:
        COMPOSER_ROOT_VERSION: dev-master

    - name: Run PHPUnit test suite
      run: composer run-script test

  mutation-tests:
    name: "Mutation Tests"

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        php-version: [ '8.0.1' ]

    runs-on: ${{ matrix.os }}

    env:
      COMPOSER_NO_INTERACTION: 1

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: composer:v2
        env:
          fail-fast: true

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer@${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        env:
          COMPOSER_ROOT_VERSION: dev-master

      - name: Run Infection
        run: composer run-script infect
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
