name: Tests

on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  PHPUnit:
    runs-on: ubuntu-latest

    env:
      COMPOSER_NO_INTERACTION: 1

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache composer dependencies
      uses: actions/cache@v1.1.0
      with:
        path: vendor
        key: composer@${{ hashFiles('**/composer.lock') }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      env:
        COMPOSER_ROOT_VERSION: dev-master

    - name: Run PHPUnit test suite
      run: composer run-script test

  mutation-tests:
    name: "Mutation Tests"

    runs-on: ubuntu-latest

    env:
      COMPOSER_NO_INTERACTION: 1

    steps:
      - uses: actions/checkout@v1

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache composer dependencies
        uses: actions/cache@v1.1.0
        with:
          path: vendor
          key: composer@${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        env:
          COMPOSER_ROOT_VERSION: dev-master

      - name: Run Infection
        run: composer run-script infect
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
